export const CALL_API = Symbol('Call API')

export const SHOW_CHALLENGE_SELECTION = "SHOW_CHALLENGE_SELECTION"
export const RESTART_CHALLENGE = "RESTART_CHALLENGE"
export const SELECT_CHALLENGE = "SELECT_CHALLENGE"

export const NEXT_CHALLENGE = "NEXT_CHALLENGE"
export const CORRECT_ENTRY = "CORRECT_ENTRY"

export const TOGGLE_KEYBOARD = "TOGGLE_KEYBOARD"
export const TOGGLE_TRANSLATIONS = "TOGGLE_TRANSLATION"

export const KEY_PRESS = "KEY_PRESS"
